package constants

var (
	Context                                                      = "context"
	Initprovidererrors                                           = "init provider error: %s"
	Providerpulltableerrors                                      = "provider pull table error: %s"
	Recordingauthentication                                      = "recording_authentication"
	Constants_2                                                  = "*"
	Constants_3                                                  = ""
	Constants_11                                                 = ""
	Constants_9                                                  = ""
	Analysisconfigerrs                                           = "analysis config err: %s"
	Errors                                                       = "errors"
	Fmt                                                          = "fmt"
	Constants_5                                                  = ""
	Constants_6                                                  = ""
	Constants_4                                                  = ""
	Accountinformationnotfound                                   = "account information not found"
	Constants_0                                                  = ""
	Notsupported                                                 = "not_supported"
	Testing                                                      = "testing"
	ZOOMAPISECRET                                                = "ZOOM_API_SECRET"
	SELEFRADATABASEDSN                                           = "SELEFRA_DATABASE_DSN"
	ZOOMAPIKEY                                                   = "ZOOM_API_KEY"
	Me                                                           = "me"
	Constants_8                                                  = ""
	UnextectedtypewantedzoomTimehaveT                            = "unextected type, wanted \"zoom.Time\", have \"%T\""
	Zoom                                                         = "zoom"
	Apikeyandapisecretmustbeconfigured                           = "api_key and api_secret must be configured"
	Meetingauthentication                                        = "meeting_authentication"
	V                                                            = "v0.0.1"
	Hostuserpostgrespasswordpassportdbnamepostgressslmodedisable = "host=127.0.0.1 user=postgres password=pass port=5432 dbname=postgres sslmode=disable"
	Constants_10                                                 = ""
	Meetingsecurity                                              = "meeting_security"
	Newclientserrs                                               = "new clients err: %s"
	NA                                                           = "N/A"
	Os                                                           = "os"
	Constants_1                                                  = "."
	Constants_7                                                  = ""
)
